[version]
source = "vcs"

[build.hooks.vcs]
version-file = "src/tree/_version.py"

[envs.default]
dependencies = [
  "pytest",
]

[envs.default.scripts]
test = "pytest {args:tests}"

[envs.lint]
detached = true
dependencies = [
  "black",
  "mypy",
  "pyright",
  "ruff",
]

[envs.lint.scripts]
typing = [
  "mypy --install-types --non-interactive",
  "pyright",
]
style = [
  "black --check --diff {args:.}",
  "ruff {args:.}",
]
fmt = [
  "black {args:.}",
  "ruff --fix {args:.}",
  "style",
]
all = [
  "style",
  "typing",
]
